/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.9
 * Generated at: 2025-08-09 16:30:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;

public final class AllMovie_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>All Movies</title>\n");
      out.write("<style>\n");
      out.write("body {\n");
      out.write("	font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n");
      out.write("	background: #f4f7fa;\n");
      out.write("	color: #333333;\n");
      out.write("	margin: 0;\n");
      out.write("	padding: 20px;\n");
      out.write("}\n");
      out.write("/* Header list styles */\n");
      out.write("ul {\n");
      out.write("	display: flex;\n");
      out.write("	justify-content: space-between;\n");
      out.write("	align-items: center;\n");
      out.write("	list-style: none;\n");
      out.write("	padding: 12px 20px;\n");
      out.write("	margin: 0 0 30px 0;\n");
      out.write("	background: #1e3a8a; /* Rich Blue */\n");
      out.write("	border-radius: 8px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("li {\n");
      out.write("	margin: 0;\n");
      out.write("	flex: 1;\n");
      out.write("	text-align: center;\n");
      out.write("	color: #ffffff;\n");
      out.write("	font-weight: 600;\n");
      out.write("	font-size: 1rem;\n");
      out.write("}\n");
      out.write("\n");
      out.write("li:first-child {\n");
      out.write("	text-align: left;\n");
      out.write("}\n");
      out.write("\n");
      out.write("li:last-child {\n");
      out.write("	text-align: right;\n");
      out.write("}\n");
      out.write("\n");
      out.write("ul li a {\n");
      out.write("	color: #93c5fd; /* Light Blue */\n");
      out.write("	text-decoration: none;\n");
      out.write("	margin-left: 1rem;\n");
      out.write("	font-weight: 500;\n");
      out.write("}\n");
      out.write("\n");
      out.write("ul li a:hover {\n");
      out.write("	text-decoration: underline;\n");
      out.write("}\n");
      out.write("\n");
      out.write("form {\n");
      out.write("	margin: 0;\n");
      out.write("	display: inline-block;\n");
      out.write("}\n");
      out.write("\n");
      out.write("input[type=\"submit\"], input[type=\"search\"] {\n");
      out.write("	font-size: 0.9rem;\n");
      out.write("	padding: 6px 12px;\n");
      out.write("	border-radius: 6px;\n");
      out.write("	border: none;\n");
      out.write("	outline: none;\n");
      out.write("	transition: background-color 0.3s ease;\n");
      out.write("}\n");
      out.write("\n");
      out.write("input[type=\"submit\"] {\n");
      out.write("	background-color: #3b82f6; /* Bright Blue */\n");
      out.write("	color: white;\n");
      out.write("	cursor: pointer;\n");
      out.write("}\n");
      out.write("\n");
      out.write("input[type=\"submit\"]:hover {\n");
      out.write("	background-color: #2563eb;\n");
      out.write("}\n");
      out.write("\n");
      out.write("input[type=\"search\"] {\n");
      out.write("	width: 180px;\n");
      out.write("	padding: 6px 10px;\n");
      out.write("	border: 1px solid #cbd5e1;\n");
      out.write("}\n");
      out.write("\n");
      out.write("input[type=\"search\"]:focus {\n");
      out.write("	border-color: #3b82f6;\n");
      out.write("	box-shadow: 0 0 5px rgba(59, 130, 246, 0.5);\n");
      out.write("}\n");
      out.write("\n");
      out.write("h1 {\n");
      out.write("	text-align: center;\n");
      out.write("	color: #1e3a8a;\n");
      out.write("	font-weight: 700;\n");
      out.write("	margin-bottom: 24px;\n");
      out.write("	font-size: 2rem;\n");
      out.write("	letter-spacing: 1px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".movie-container {\n");
      out.write("	display: flex;\n");
      out.write("	flex-wrap: wrap;\n");
      out.write("	justify-content: center;\n");
      out.write("	gap: 24px;\n");
      out.write("	max-width: 1100px;\n");
      out.write("	margin: 0 auto 40px auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".movie-item {\n");
      out.write("	background: white;\n");
      out.write("	border-radius: 14px;\n");
      out.write("	box-shadow: 0 8px 16px rgba(0, 0, 0, 0.12);\n");
      out.write("	width: 240px;\n");
      out.write("	overflow: hidden;\n");
      out.write("	transition: transform 0.3s ease, box-shadow 0.3s ease;\n");
      out.write("	cursor: pointer;\n");
      out.write("	display: flex;\n");
      out.write("	flex-direction: column;\n");
      out.write("	text-align: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".movie-item:hover {\n");
      out.write("	transform: translateY(-8px);\n");
      out.write("	box-shadow: 0 16px 32px rgba(0, 0, 0, 0.18);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".movie-item img {\n");
      out.write("	width: 100%;\n");
      out.write("	height: 320px;\n");
      out.write("	object-fit: cover;\n");
      out.write("	border-bottom: 3px solid #1e3a8a;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".movie-item a {\n");
      out.write("	color: inherit;\n");
      out.write("	text-decoration: none;\n");
      out.write("	display: block;\n");
      out.write("	height: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".movie-item h4 {\n");
      out.write("	margin: 8px 0;\n");
      out.write("	color: #1e3a8a;\n");
      out.write("	font-weight: 600;\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media ( max-width : 1000px) {\n");
      out.write("	.movie-container {\n");
      out.write("		max-width: 90%;\n");
      out.write("		gap: 18px;\n");
      out.write("	}\n");
      out.write("	.movie-item {\n");
      out.write("		width: 200px;\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media ( max-width : 600px) {\n");
      out.write("	.movie-container {\n");
      out.write("		max-width: 100%;\n");
      out.write("		gap: 16px;\n");
      out.write("		justify-content: center;\n");
      out.write("	}\n");
      out.write("	.movie-item {\n");
      out.write("		width: 90%;\n");
      out.write("		max-width: 320px;\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<ul>\n");
      out.write("		<li>\n");
      out.write("			<form action=\"/MovieReview/index\">\n");
      out.write("				<input type=\"submit\" value=\"Home\">\n");
      out.write("			</form>\n");
      out.write("			<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AllMovie\">\n");
      out.write("				<input type=\"submit\" value=\"All Movie\">\n");
      out.write("			</form>\n");
      out.write("		</li>\n");
      out.write("		<li>\n");
      out.write("			<form action=\"/MovieReview/SelectedFlim\">\n");
      out.write("				<input type=\"search\" name=\"search\" placeholder=\"Enter Film Name\" />\n");
      out.write("				<input type=\"submit\" value=\"Search\" />\n");
      out.write("			</form>\n");
      out.write("		</li>\n");
      out.write("		<li>\n");
      out.write("			");

			if (session.getAttribute("UserName") == null && session.getAttribute("AdminName") == null) {
			
      out.write(" <a href=\"LoginCheck.jsp\">User Login</a> <a\n");
      out.write("			href=\"AdminLoginCheck.jsp\">Admin Login</a> <a href=\"CreateUser.jsp\">Create\n");
      out.write("				New Account</a> ");

 } else if (session.getAttribute("UserName") != null) {
 
      out.write(' ');
      out.print(session.getAttribute("UserName"));
      out.write("\n");
      out.write("			<form action=\"/MovieReview/profile\" style=\"display: inline\">\n");
      out.write("				<input type=\"submit\" value=\"Profile\">\n");
      out.write("			</form> ");

 } else if (session.getAttribute("AdminName") != null) {
 
      out.write(' ');
      out.print(session.getAttribute("AdminName"));
      out.write("\n");
      out.write("			<form action=\"/MovieReview/profile\" style=\"display: inline\">\n");
      out.write("				<input type=\"submit\" value=\"Profile\">\n");
      out.write("			</form> ");

 }
 
      out.write("\n");
      out.write("		</li>\n");
      out.write("	</ul>\n");
      out.write("	<h1>All Movies</h1>\n");
      out.write("	<div class=\"movie-container\">\n");
      out.write("		");

		List movies = (List) session.getAttribute("movies");
		if (movies != null && !movies.isEmpty()) {
			for (int i = 0; i < movies.size(); i++) {
				request.setAttribute("movie", movies.get(i));
		
      out.write("\n");
      out.write("		<div class=\"movie-item\">\n");
      out.write("			<a href=\"/MovieReview/SelectedFlim?search=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${movie.movieName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> <img\n");
      out.write("				src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/image/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${movie.movieImageURL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\n");
      out.write("				alt=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${movie.movieName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\n");
      out.write("				<h4>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${movie.movieName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\n");
      out.write("				<h4>Rating: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${movie.movieRating}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\n");
      out.write("				<h4>Released: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${movie.releaseDate}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\n");
      out.write("				<h4>Genre: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${movie.genre}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\n");
      out.write("			</a>\n");
      out.write("		</div>\n");
      out.write("		");

		}
		} else {
		
      out.write("\n");
      out.write("		<p style=\"text-align: center; width: 100%; color: #6b7280;\">No\n");
      out.write("			movies available.</p>\n");
      out.write("		");

		}
		
      out.write("\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
