/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.9
 * Generated at: 2025-08-09 16:59:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import DAO.User;
import DAO.Admin;
import DAO.Review;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("DAO.User");
    _jspx_imports_classes.add("DAO.Review");
    _jspx_imports_classes.add("DAO.Admin");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>User/Admin Profile</title>\n");
      out.write("<style>\n");
      out.write("body {\n");
      out.write("	font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\n");
      out.write("	background: #f4f7fa;\n");
      out.write("	margin: 0;\n");
      out.write("	padding: 20px;\n");
      out.write("	color: #333;\n");
      out.write("}\n");
      out.write("/* Header list styles */\n");
      out.write("ul {\n");
      out.write("	display: flex;\n");
      out.write("	justify-content: space-between;\n");
      out.write("	align-items: center;\n");
      out.write("	list-style: none;\n");
      out.write("	padding: 12px 20px;\n");
      out.write("	margin: 0 0 30px 0;\n");
      out.write("	background: #1e3a8a; /* Rich Blue */\n");
      out.write("	border-radius: 8px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("li {\n");
      out.write("	margin: 0;\n");
      out.write("	flex: 1;\n");
      out.write("	text-align: center;\n");
      out.write("	color: #ffffff;\n");
      out.write("	font-weight: 600;\n");
      out.write("	font-size: 1rem;\n");
      out.write("}\n");
      out.write("\n");
      out.write("li:first-child {\n");
      out.write("	text-align: left;\n");
      out.write("}\n");
      out.write("\n");
      out.write("li:last-child {\n");
      out.write("	text-align: right;\n");
      out.write("}\n");
      out.write("\n");
      out.write("ul li a {\n");
      out.write("	color: #93c5fd; /* Light Blue */\n");
      out.write("	text-decoration: none;\n");
      out.write("	margin-left: 1rem;\n");
      out.write("	font-weight: 500;\n");
      out.write("}\n");
      out.write("\n");
      out.write("ul li a:hover {\n");
      out.write("	text-decoration: underline;\n");
      out.write("}\n");
      out.write("\n");
      out.write("form {\n");
      out.write("	margin: 0;\n");
      out.write("	display: inline-block;\n");
      out.write("}\n");
      out.write("\n");
      out.write("input[type=\"submit\"], input[type=\"search\"] {\n");
      out.write("	font-size: 0.9rem;\n");
      out.write("	padding: 6px 12px;\n");
      out.write("	border-radius: 6px;\n");
      out.write("	border: none;\n");
      out.write("	outline: none;\n");
      out.write("	transition: background-color 0.3s ease;\n");
      out.write("}\n");
      out.write("\n");
      out.write("input[type=\"submit\"] {\n");
      out.write("	background-color: #3b82f6; /* Bright Blue */\n");
      out.write("	color: white;\n");
      out.write("	cursor: pointer;\n");
      out.write("}\n");
      out.write("\n");
      out.write("input[type=\"submit\"]:hover {\n");
      out.write("	background-color: #2563eb;\n");
      out.write("}\n");
      out.write("\n");
      out.write("input[type=\"search\"] {\n");
      out.write("	width: 180px;\n");
      out.write("	padding: 6px 10px;\n");
      out.write("	border: 1px solid #cbd5e1;\n");
      out.write("}\n");
      out.write("\n");
      out.write("input[type=\"search\"]:focus {\n");
      out.write("	border-color: #3b82f6;\n");
      out.write("	box-shadow: 0 0 5px rgba(59, 130, 246, 0.5);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".profile-card {\n");
      out.write("	max-width: 800px;\n");
      out.write("	margin: 40px auto;\n");
      out.write("	background: #fff;\n");
      out.write("	border-radius: 14px;\n");
      out.write("	box-shadow: 0 8px 20px rgba(0, 0, 0, 0.12);\n");
      out.write("	padding: 25px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("h1, h2 {\n");
      out.write("	color: #1e3a8a;\n");
      out.write("	margin-bottom: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("h2 {\n");
      out.write("	font-size: 1.2rem;\n");
      out.write("	font-weight: 500;\n");
      out.write("	color: #374151;\n");
      out.write("}\n");
      out.write("\n");
      out.write("p {\n");
      out.write("	margin: 6px 0;\n");
      out.write("	font-size: 1rem;\n");
      out.write("	color: #555;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".logout-btn {\n");
      out.write("	background: #ef4444;\n");
      out.write("	color: white;\n");
      out.write("	border: none;\n");
      out.write("	padding: 10px 16px;\n");
      out.write("	border-radius: 6px;\n");
      out.write("	font-size: 1rem;\n");
      out.write("	cursor: pointer;\n");
      out.write("	margin-top: 15px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".logout-btn:hover {\n");
      out.write("	background: #dc2626;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".form-section {\n");
      out.write("	margin-top: 30px;\n");
      out.write("	padding: 20px;\n");
      out.write("	background: #f9fafb;\n");
      out.write("	border-radius: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".form-section h1 {\n");
      out.write("	color: #1e3a8a;\n");
      out.write("	font-size: 1.5rem;\n");
      out.write("	margin-bottom: 15px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".form-section label {\n");
      out.write("	font-weight: 600;\n");
      out.write("	color: #374151;\n");
      out.write("	display: block;\n");
      out.write("	margin-top: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".form-section input[type=\"text\"], .form-section input[type=\"date\"] {\n");
      out.write("	width: 100%;\n");
      out.write("	padding: 8px;\n");
      out.write("	margin-top: 4px;\n");
      out.write("	border-radius: 6px;\n");
      out.write("	border: 1px solid #cbd5e1;\n");
      out.write("	margin-bottom: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".form-section input[type=\"submit\"] {\n");
      out.write("	background: #3b82f6;\n");
      out.write("	color: white;\n");
      out.write("	border: none;\n");
      out.write("	padding: 10px 16px;\n");
      out.write("	border-radius: 6px;\n");
      out.write("	font-size: 1rem;\n");
      out.write("	cursor: pointer;\n");
      out.write("	margin-top: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".form-section input[type=\"submit\"]:hover {\n");
      out.write("	background: #2563eb;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<ul>\n");
      out.write("		<li>\n");
      out.write("			<form action=\"/MovieReview/index\">\n");
      out.write("				<input type=\"submit\" value=\"Home\">\n");
      out.write("			</form>\n");
      out.write("			<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AllMovie\">\n");
      out.write("				<input type=\"submit\" value=\"All Movie\">\n");
      out.write("			</form>\n");
      out.write("		</li>\n");
      out.write("		<li>\n");
      out.write("			<form action=\"/MovieReview/SelectedFlim\">\n");
      out.write("				<input type=\"search\" name=\"search\" placeholder=\"Enter Film Name\" />\n");
      out.write("				<input type=\"submit\" value=\"Search\" />\n");
      out.write("			</form>\n");
      out.write("		</li>\n");
      out.write("		<li>\n");
      out.write("			");

			if (session.getAttribute("UserName") == null && session.getAttribute("AdminName") == null) {
			
      out.write(" <a href=\"LoginCheck.jsp\">User Login</a> <a\n");
      out.write("			href=\"AdminLoginCheck.jsp\">Admin Login</a> <a href=\"CreateUser.jsp\">Create\n");
      out.write("				New Account</a> ");

 } else if (session.getAttribute("UserName") != null) {
 
      out.write(' ');
      out.print(session.getAttribute("UserName"));
      out.write("\n");
      out.write("			<form action=\"/MovieReview/profile\" style=\"display: inline\">\n");
      out.write("				<input type=\"submit\" value=\"Profile\">\n");
      out.write("			</form> ");

 } else if (session.getAttribute("AdminName") != null) {
 
      out.write(' ');
      out.print(session.getAttribute("AdminName"));
      out.write("\n");
      out.write("			<form action=\"/MovieReview/profile\" style=\"display: inline\">\n");
      out.write("				<input type=\"submit\" value=\"Profile\">\n");
      out.write("			</form> ");

 }
 
      out.write("\n");
      out.write("		</li>\n");
      out.write("	</ul>\n");
      out.write("	");

	List<User> userList = null;
	List<Admin> adminList = null;
	List<Review> reviewList = null;
	if (session.getAttribute("UserName") != null) {
		userList = (List<User>) session.getAttribute("UserDetails");
		reviewList = (List<Review>) session.getAttribute("comments");
		if (userList != null && !userList.isEmpty()) {
			User u = userList.get(0);
	
      out.write("\n");
      out.write("	<div class=\"profile-card\">\n");
      out.write("		<h1>User Profile</h1>\n");
      out.write("		<h2>\n");
      out.write("			UserName:\n");
      out.write("			");
      out.print(u.getUserName());
      out.write("</h2>\n");
      out.write("		<p>\n");
      out.write("			Email:\n");
      out.write("			");
      out.print(u.getEmail());
      out.write("</p>\n");
      out.write("		<p>\n");
      out.write("			Password:\n");
      out.write("			");
      out.print(u.getPassword());
      out.write("</p>\n");
      out.write("		<form action=\"/MovieReview/logout\">\n");
      out.write("			<input type=\"submit\" class=\"logout-btn\" value=\"Log out\">\n");
      out.write("			<div class=\"review-section\">\n");
      out.write("				<h2>Your Recent Reviews</h2>\n");
      out.write("				");

				if (reviewList != null && !reviewList.isEmpty()) {
					for (int i = 0; i < reviewList.size() && i < 3; i++) {
						Review r = reviewList.get(i);
				
      out.write("\n");
      out.write("				<div class=\"review-card\">\n");
      out.write("					<h3>");
      out.print(r.getMovieName());
      out.write("</h3>\n");
      out.write("					<p>\n");
      out.write("						Rating:\n");
      out.write("						");
      out.print(r.getUserRating());
      out.write("/10\n");
      out.write("					</p>\n");
      out.write("					<p>");
      out.print(r.getReview());
      out.write("</p>\n");
      out.write("					<small>Posted on: ");
      out.print(r.getCreatedAt());
      out.write("</small>\n");
      out.write("				</div>\n");
      out.write("				");

				}
				} else {
				
      out.write("\n");
      out.write("				<p>You have not posted any reviews yet.</p>\n");
      out.write("				");

				}
				
      out.write("\n");
      out.write("			</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("	</div>\n");
      out.write("	");

	}
	} else if (session.getAttribute("AdminName") != null) {
	adminList = (List<Admin>) session.getAttribute("AdminDetails");
	if (adminList != null && !adminList.isEmpty()) {
	Admin a = adminList.get(0);
	
      out.write("\n");
      out.write("	<div class=\"profile-card\">\n");
      out.write("		<h1>Admin Profile</h1>\n");
      out.write("		<h2>\n");
      out.write("			AdminName:\n");
      out.write("			");
      out.print(a.getAdminName());
      out.write("</h2>\n");
      out.write("		<p>\n");
      out.write("			Email:\n");
      out.write("			");
      out.print(a.getEmail());
      out.write("</p>\n");
      out.write("		<p>\n");
      out.write("			Password:\n");
      out.write("			");
      out.print(a.getPassword());
      out.write("</p>\n");
      out.write("		<form action=\"/MovieReview/logout\">\n");
      out.write("			<input type=\"submit\" class=\"logout-btn\" value=\"Log out\">\n");
      out.write("		</form>\n");
      out.write("\n");
      out.write("		<div class=\"form-section\">\n");
      out.write("			<h1>Add Movies</h1>\n");
      out.write("			<form action=\"/MovieReview/AddMovie\">\n");
      out.write("				<label>MovieName</label> <input type=\"text\" name=\"MovieName\"\n");
      out.write("					required> <label>Genre</label> <input type=\"text\"\n");
      out.write("					name=\"Genre\" required> <label>ReleaseDate</label> <input\n");
      out.write("					type=\"date\" name=\"ReleaseDate\" required> <label>Length</label>\n");
      out.write("				<input type=\"text\" name=\"Length\" required> <label>MovieImageURL</label>\n");
      out.write("				<input type=\"text\" name=\"MovieImageURL\" required> <label>Trailer\n");
      out.write("					Link</label> <input type=\"text\" name=\"Trailer\" required> <input\n");
      out.write("					type=\"submit\" value=\"Add\">\n");
      out.write("			</form>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	");

	} else {
	
      out.write("\n");
      out.write("	<p style=\"text-align: center;\">No admin details found.</p>\n");
      out.write("	");

	}
	}
	
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
